# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Ali Farooqui Limited
tagline:          'DevSecOps Consultancy'
description:      'An experienced DevSecOps engineer with a strong systems administration and automation background, I specialise in infrastructure as code, security and configuration management. I help create processes that remove impediments in the CI/CD pipelines for large scale agile infrastructure deployments.'
url:              https://alifarooqui.net
baseurl:          /

author:
  name:           'Ali Farooqui'
  url:            https://alifarooqui.net

paginate:         5

# Custom vars
version:          v2.0.0

github:
  repo:           https://alifarooqui.net
