# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Ali Farooqui Limited
tagline:          'DevSecOps Consultancy'
description:      'An experienced DevSecOps engineer with a strong systems administration and automation background, I specialise in infrastructure as code, security and configuration management. I help create processes that remove impediments in the CI/CD pipelines for large scale agile infrastructure deployments.'
url:              https://alimurtazafarooqui.github.io/
baseurl:          /

author:
  name:           'Ali Farooqui'
  url:            https://alimurtazafarooqui.github.io/

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
